"""ADD: added user_id to listings and related it to user

Revision ID: 9858f10c0153
Revises: bf9ab2dd1c6d
Create Date: 2024-12-30 15:04:52.979876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9858f10c0153'
down_revision = 'bf9ab2dd1c6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_listings_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_listings_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
