"""changed table name

Revision ID: cce973004c18
Revises: fe94bf987669
Create Date: 2024-12-18 14:22:51.955375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cce973004c18'
down_revision = 'fe94bf987669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bedroom', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bathroom', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('amenity', sa.String(), nullable=True))
        batch_op.alter_column('kitchen',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_column('bedroom_amt')
        batch_op.drop_column('bathroom_amt')
        batch_op.drop_column('amenities')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amenities', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('bathroom_amt', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('bedroom_amt', sa.INTEGER(), nullable=True))
        batch_op.alter_column('kitchen',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.drop_column('amenity')
        batch_op.drop_column('bathroom')
        batch_op.drop_column('bedroom')

    # ### end Alembic commands ###
